//! Generate a self-contained CI harness for a project's scenarios.
//!
//! The desktop app starts each emulator itself, with the topology hardcoded
//! across `handlers/{azurite,sql_emulator,cosmos_emulator,sb_emulator}.rs`. CI
//! can't call those — they drive UI signals and manage long-lived child
//! processes. What CI needs is the same topology as a compose file it can bring
//! up itself.
//!
//! Two of the three outputs are static (images, ports, healthchecks); the third
//! is not. The Service Bus emulator refuses to start unless every queue is
//! declared up front in `Config.json`, and that list comes from scanning the
//! project's workflows. Generating it here rather than committing it by hand is
//! the difference between a harness that stays in sync with the workflows and
//! one that silently rots — a queue added to a workflow but not to a
//! hand-maintained config fails at send time, deep inside a scenario.

use std::path::{Path, PathBuf};

use crate::handlers::sb_emulator::{
    is_valid_sb_queue_name, SB_EMULATOR_IMAGE, SB_EMULATOR_MAX_ENTITIES, SB_EMULATOR_PORT,
};
use crate::handlers::{cosmos_emulator, sql_emulator};
use crate::services::sb_check;

/// Azurite isn't started from a container by the desktop app (it runs the npm
/// package directly), so this image is CI-only.
const AZURITE_IMAGE: &str = "mcr.microsoft.com/azure-storage/azurite:latest";

/// Where the generated Config.json is mounted from, relative to the compose file.
const SB_CONFIG_DIR: &str = "sb-config";

pub struct Generated {
    pub files: Vec<PathBuf>,
    /// Queues written into Config.json, in the order the emulator will see them.
    pub queues: Vec<String>,
    /// Queues dropped because the emulator's entity ceiling was reached.
    pub dropped: Vec<String>,
    /// Non-fatal notes worth showing the user (skipped names, sentinel used).
    pub notes: Vec<String>,
}

/// Write `docker-compose.test.yml` and `sb-config/Config.json` into `out_dir`.
pub fn generate(logic_apps_dir: &str, out_dir: &Path) -> Result<Generated, String> {
    std::fs::create_dir_all(out_dir).map_err(|e| e.to_string())?;
    let config_dir = out_dir.join(SB_CONFIG_DIR);
    std::fs::create_dir_all(&config_dir).map_err(|e| e.to_string())?;

    let (_ns, detected) = sb_check::detect_sb_queues(logic_apps_dir);
    let mut notes = Vec::new();

    // Same filtering the desktop path applies: an invalid name surfaces from the
    // emulator as a regex assertion deep inside FluentAssertions, so drop it here
    // where we can say which name was wrong.
    let mut queues: Vec<(String, bool)> = Vec::new();
    for q in &detected {
        let name = q.queue.trim();
        if name.is_empty() || !is_valid_sb_queue_name(name) {
            notes.push(format!("skipped invalid queue name '{}'", q.queue));
            continue;
        }
        if !queues.iter().any(|(n, _): &(String, bool)| n == name) {
            queues.push((name.to_string(), q.requires_session));
        }
    }

    // An empty Queues array makes the emulator host throw a NullReferenceException
    // on boot, so a project with no Service Bus usage still needs one entry.
    if queues.is_empty() {
        queues.push(("ais.default".to_string(), false));
        notes.push("no queues detected — wrote sentinel queue 'ais.default'".to_string());
    }

    let dropped: Vec<String> = if queues.len() > SB_EMULATOR_MAX_ENTITIES {
        let rest = queues[SB_EMULATOR_MAX_ENTITIES..]
            .iter()
            .map(|(n, _)| n.clone())
            .collect();
        queues.truncate(SB_EMULATOR_MAX_ENTITIES);
        rest
    } else {
        Vec::new()
    };

    let compose_path = out_dir.join("docker-compose.test.yml");
    std::fs::write(&compose_path, compose_yaml()).map_err(|e| e.to_string())?;

    let config_path = config_dir.join("Config.json");
    std::fs::write(&config_path, config_json(&queues)).map_err(|e| e.to_string())?;

    Ok(Generated {
        files: vec![compose_path, config_path],
        queues: queues.into_iter().map(|(n, _)| n).collect(),
        dropped,
        notes,
    })
}

/// The compose file. Ports match the desktop app's so a scenario needs no
/// rewriting between a laptop and CI.
fn compose_yaml() -> String {
    format!(
        r#"# Generated by `ais-test --emit-ci`. Do not edit by hand — regenerate instead.
#
# Brings up the four emulators a scenario run needs. Ports match what the
# desktop app uses, so the same scenario JSON runs unchanged in both places.
#
#   docker compose -f docker-compose.test.yml up -d --wait
#
# `--wait` matters: the Service Bus emulator only becomes usable after SQL Edge
# passes its healthcheck, and Cosmos takes the longest of the four to accept
# connections. Without it the first scenario races the containers.
name: ais-runner-test

services:
  azurite:
    container_name: ais-test-azurite
    image: {azurite}
    command: azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --skipApiVersionCheck
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 10000 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  sqledge:
    container_name: ais-test-sqledge
    image: {sql}
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "{pw}"
    ports:
      - "{sql_port}:1433"
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/127.0.0.1/1433' 2>/dev/null"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 30s

  sbemulator:
    container_name: ais-test-sb
    image: {sb}
    volumes:
      - ./{config_dir}:/ServiceBus_Emulator/ConfigFiles
    ports:
      - "{sb_port}:{sb_port}"
    environment:
      SQL_SERVER: sqledge
      MSSQL_SA_PASSWORD: "{pw}"
      ACCEPT_EULA: "Y"
    depends_on:
      sqledge:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/127.0.0.1/{sb_port}' 2>/dev/null"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 20s

  # Preview-quality image and the slowest of the four to boot. If it turns out
  # to be the flakiest part of the pipeline, run it as a separate compose
  # profile and tag Cosmos-dependent scenarios so the rest can still gate.
  cosmos:
    container_name: ais-test-cosmos
    image: {cosmos}
    ports:
      - "{cosmos_api}:{cosmos_api}"
      - "{cosmos_ui}:{cosmos_ui}"
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/127.0.0.1/{cosmos_api}' 2>/dev/null"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s
"#,
        azurite = AZURITE_IMAGE,
        sql = sql_emulator::SQL_IMAGE,
        sb = SB_EMULATOR_IMAGE,
        cosmos = cosmos_emulator::COSMOS_IMAGE,
        pw = sql_emulator::SA_PASSWORD,
        sql_port = sql_emulator::SQL_PORT,
        sb_port = SB_EMULATOR_PORT,
        cosmos_api = cosmos_emulator::COSMOS_API_PORT,
        cosmos_ui = cosmos_emulator::COSMOS_UI_PORT,
        config_dir = SB_CONFIG_DIR,
    )
}

/// The emulator's Config.json. The namespace name is fixed: the emulator only
/// accepts `sbemulatorns`, and any other value fails at boot.
fn config_json(queues: &[(String, bool)]) -> String {
    let entries: Vec<serde_json::Value> = queues
        .iter()
        .map(|(name, session)| {
            serde_json::json!({
                "Name": name,
                "Properties": {
                    "DeadLetteringOnMessageExpiration": false,
                    "DefaultMessageTimeToLive": "PT1H",
                    "LockDuration": "PT1M",
                    "MaxDeliveryCount": 10,
                    "RequiresDuplicateDetection": false,
                    "RequiresSession": session
                }
            })
        })
        .collect();

    let root = serde_json::json!({
        "UserConfig": {
            "Namespaces": [{
                "Name": "sbemulatorns",
                "Queues": entries
            }],
            "Logging": { "Type": "File" }
        }
    });

    serde_json::to_string_pretty(&root).unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn config_json_has_the_shape_the_emulator_requires() {
        let json = config_json(&[("a.b".into(), false), ("c.d".into(), true)]);
        let v: serde_json::Value = serde_json::from_str(&json).unwrap();

        // Namespace name is not configurable — the emulator rejects anything else.
        assert_eq!(v["UserConfig"]["Namespaces"][0]["Name"], "sbemulatorns");
        // `Logging`, not `LoggingConfig` — the desktop path treats the latter as
        // a corrupt file and regenerates.
        assert!(v["UserConfig"]["Logging"].is_object());

        let queues = v["UserConfig"]["Namespaces"][0]["Queues"]
            .as_array()
            .unwrap();
        assert_eq!(queues.len(), 2);
        assert_eq!(queues[0]["Name"], "a.b");
        assert_eq!(queues[1]["Properties"]["RequiresSession"], true);
    }

    #[test]
    fn compose_exposes_every_port_a_scenario_talks_to() {
        let yaml = compose_yaml();
        for port in ["10000", "10001", "10002", "1433", "5672", "8081"] {
            assert!(yaml.contains(port), "compose is missing port {port}");
        }
        // The SB emulator must not start before SQL Edge is healthy.
        assert!(yaml.contains("condition: service_healthy"));
        assert!(yaml.contains(&format!(
            "./{SB_CONFIG_DIR}:/ServiceBus_Emulator/ConfigFiles"
        )));
    }

    #[test]
    fn generate_writes_both_files_and_falls_back_to_a_sentinel_queue() {
        let tmp = tempfile::tempdir().unwrap();
        // An empty project detects no queues, which is the case that crashes the
        // emulator if the sentinel is missing.
        let empty_project = tempfile::tempdir().unwrap();

        let g = generate(empty_project.path().to_str().unwrap(), tmp.path()).unwrap();

        assert_eq!(g.files.len(), 2);
        assert!(tmp.path().join("docker-compose.test.yml").is_file());
        assert!(tmp.path().join(SB_CONFIG_DIR).join("Config.json").is_file());
        assert_eq!(g.queues, vec!["ais.default".to_string()]);
        assert!(g.notes.iter().any(|n| n.contains("sentinel")));
    }
}
